### PR TITLE
initial import of WPI-{data,control}+CWL analysis

### PR DESCRIPTION
**Pull request by mr-c**
TODO (in this PR, or another): provide concrete + runnable CWL examples for each pattern that CWL supports directly or indirectly.

Partial fulfilment of #1

### CODE REVIEW

**Comment by mr-c** [comment]
Also of interest to @illusional if I remember correctly.

**Comment by ghost** [comment]
Very nice analysis @mr-c ! I'm not clear about the organization of the content

1. Currently this is not linked to from the main Readme. Is the idea that we will link once the content is more complete?
2. Why is there one Readme under `workflow_patterns_initiative` and then other under `workflow_patterns_initiative/data` and neither refers to the other?

Thank you.

**Comment by mr-c** [comment]
@kaushik-work Thanks! I've added interstitial links from the main README on down.

**Comment by mr-c** [comment]
I've added an analysis of CWL against the WPI control patterns

**Comment by ghost** [comment]
Excellent. Thank you for this analysis @mr-c

**Pull request merged**
